package com.sandy.jnmaker.ui.dialogs.wm ;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

public abstract class WMPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 9015449326144115519L;
 
    public WMPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel wordLabel = new javax.swing.JLabel();
        wordTF = new javax.swing.JTextField();
        getMeaningBtn = new javax.swing.JButton();
        javax.swing.JLabel meaningLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp1 = new javax.swing.JScrollPane();
        meaningTF = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        wordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        wordLabel.setText("Word");

        wordTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        getMeaningBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        getMeaningBtn.setText("Get meaning");

        meaningLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        meaningLabel.setText("Meaning");

        meaningTF.setColumns(20);
        meaningTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        meaningTF.setLineWrap(true);
        meaningTF.setRows(5);
        meaningTF.setTabSize(4);
        meaningTF.setWrapStyleWord(true);
        sp1.setViewportView(meaningTF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getMeaningBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wordLabel)
                            .addComponent(meaningLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMeaningBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meaningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton getMeaningBtn;
    protected javax.swing.JTextArea meaningTF;
    protected javax.swing.JTextField wordTF;
    // End of variables declaration//GEN-END:variables
}
