package com.sandy.jnmaker.ui.dialogs.qa ;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

/**
 * This file has been generated by NetBeans. If you have to add logic, please
 * do so in derived classes.
 * 
 * @author sandeep
 */
public abstract class QAPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 1L;
    
    public QAPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel enterQLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane enterQTextAreaSP = new javax.swing.JScrollPane();
        questionTextArea = new javax.swing.JTextArea();
        javax.swing.JSeparator separator = new javax.swing.JSeparator();
        javax.swing.JLabel enterALabel = new javax.swing.JLabel();
        javax.swing.JScrollPane enterAnswerTextAreaSP = new javax.swing.JScrollPane();
        answerTextArea = new javax.swing.JTextArea();
        ansImgBtn = new javax.swing.JButton();
        ansImgLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.lightGray);
        setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        enterQLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        enterQLabel.setText("Enter question :");

        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(3);
        questionTextArea.setTabSize(4);
        questionTextArea.setWrapStyleWord(true);
        questionTextArea.setMargin(new java.awt.Insets(2, 2, 2, 2));
        enterQTextAreaSP.setViewportView(questionTextArea);

        enterALabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        enterALabel.setText("Enter answer :");

        answerTextArea.setColumns(20);
        answerTextArea.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        answerTextArea.setLineWrap(true);
        answerTextArea.setRows(5);
        answerTextArea.setTabSize(4);
        answerTextArea.setWrapStyleWord(true);
        answerTextArea.setMargin(new java.awt.Insets(2, 2, 2, 2));
        enterAnswerTextAreaSP.setViewportView(answerTextArea);

        ansImgBtn.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        ansImgBtn.setText("Image");
        ansImgBtn.setIconTextGap(0);
        ansImgBtn.setPreferredSize(new java.awt.Dimension(42, 20));

        ansImgLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        ansImgLabel.setForeground(new java.awt.Color(0, 44, 255));
        ansImgLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ansImgLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterAnswerTextAreaSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(enterQTextAreaSP)
                    .addComponent(separator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterQLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterALabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ansImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterQLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterQTextAreaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterALabel)
                    .addComponent(ansImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansImgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterAnswerTextAreaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton ansImgBtn;
    protected javax.swing.JLabel ansImgLabel;
    protected javax.swing.JTextArea answerTextArea;
    protected javax.swing.JTextArea questionTextArea;
    // End of variables declaration//GEN-END:variables
}
