package com.sandy.jnmaker.ui.dialogs.definition;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

public abstract class DefinitionPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 1L;

    public DefinitionPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel termLabel = new javax.swing.JLabel();
        termTF = new javax.swing.JTextField();
        javax.swing.JLabel defLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp1 = new javax.swing.JScrollPane();
        definitionTF = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        termLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        termLabel.setText("Term");

        termTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        defLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        defLabel.setText("Definition");

        definitionTF.setColumns(20);
        definitionTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        definitionTF.setLineWrap(true);
        definitionTF.setRows(5);
        definitionTF.setTabSize(4);
        definitionTF.setWrapStyleWord(true);
        sp1.setViewportView(definitionTF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(termLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(termTF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(termLabel)
                    .addComponent(termTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea definitionTF;
    protected javax.swing.JTextField termTF;
    // End of variables declaration//GEN-END:variables
}
