package com.sandy.jnmaker.ui.dialogs.truefalse;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

public abstract class TFPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = -995072693854941335L;
    
    public TFPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel stmtLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp1 = new javax.swing.JScrollPane();
        stmtTextArea = new javax.swing.JTextArea();
        trueFalseCheckBox = new javax.swing.JCheckBox();
        javax.swing.JLabel justificationLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp2 = new javax.swing.JScrollPane();
        justTextArea = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        stmtLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        stmtLabel.setText("Statement");

        stmtTextArea.setColumns(20);
        stmtTextArea.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        stmtTextArea.setLineWrap(true);
        stmtTextArea.setRows(5);
        stmtTextArea.setTabSize(4);
        stmtTextArea.setWrapStyleWord(true);
        sp1.setViewportView(stmtTextArea);

        trueFalseCheckBox.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        trueFalseCheckBox.setText("True ?");

        justificationLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        justificationLabel.setText("Justification");

        justTextArea.setColumns(20);
        justTextArea.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        justTextArea.setLineWrap(true);
        justTextArea.setRows(5);
        justTextArea.setTabSize(4);
        justTextArea.setWrapStyleWord(true);
        sp2.setViewportView(justTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stmtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trueFalseCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(justificationLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sp2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stmtLabel)
                    .addComponent(trueFalseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(justificationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea justTextArea;
    protected javax.swing.JTextArea stmtTextArea;
    protected javax.swing.JCheckBox trueFalseCheckBox;
    // End of variables declaration//GEN-END:variables
}
