package com.sandy.jnmaker.ui.dialogs.spellbee;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

public abstract class SpellbeePanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 1L;

    public SpellbeePanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel wordLabel = new javax.swing.JLabel();
        wordTF = new javax.swing.JTextField();
        downloadBtn = new javax.swing.JButton();
        playBtn = new javax.swing.JButton();
        javax.swing.JLabel meaningLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp1 = new javax.swing.JScrollPane();
        meaningTF = new javax.swing.JTextArea();
        msgLabel = new javax.swing.JLabel();
        javax.swing.JLabel pronunciationLabel = new javax.swing.JLabel();
        pronunciationTF = new javax.swing.JTextField();

        setBackground(java.awt.Color.lightGray);

        wordLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        wordLabel.setText("Word");

        wordTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        downloadBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        downloadBtn.setText("Download");

        playBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        playBtn.setText("Play");

        meaningLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        meaningLabel.setText("Meaning");

        meaningTF.setColumns(20);
        meaningTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        meaningTF.setLineWrap(true);
        meaningTF.setRows(5);
        meaningTF.setTabSize(4);
        meaningTF.setWrapStyleWord(true);
        sp1.setViewportView(meaningTF);

        msgLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        msgLabel.setForeground(java.awt.Color.blue);
        msgLabel.setText("message");

        pronunciationLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        pronunciationLabel.setText("Pronunciation");

        pronunciationTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp1)
                    .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meaningLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pronunciationLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(downloadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pronunciationTF))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordLabel)
                    .addComponent(wordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadBtn)
                    .addComponent(playBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pronunciationLabel)
                    .addComponent(pronunciationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(meaningLabel)
                .addGap(12, 12, 12)
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton downloadBtn;
    protected javax.swing.JTextArea meaningTF;
    protected javax.swing.JLabel msgLabel;
    protected javax.swing.JButton playBtn;
    protected javax.swing.JTextField pronunciationTF;
    protected javax.swing.JTextField wordTF;
    // End of variables declaration//GEN-END:variables
}
