package com.sandy.jnmaker.ui.dialogs.event ;

import com.sandy.jnmaker.ui.dialogs.AbstractNotePanel;

public abstract class EventPanelUI extends AbstractNotePanel {

    private static final long serialVersionUID = 1L;

    public EventPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel timeLabel = new javax.swing.JLabel();
        timeTF = new javax.swing.JTextField();
        javax.swing.JLabel eventLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane sp1 = new javax.swing.JScrollPane();
        eventTF = new javax.swing.JTextArea();

        setBackground(java.awt.Color.lightGray);

        timeLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        timeLabel.setText("Time");

        timeTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        eventLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        eventLabel.setText("Event");

        eventTF.setColumns(20);
        eventTF.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eventTF.setLineWrap(true);
        eventTF.setRows(5);
        eventTF.setTabSize(4);
        eventTF.setWrapStyleWord(true);
        sp1.setViewportView(eventTF);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeTF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eventLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea eventTF;
    protected javax.swing.JTextField timeTF;
    // End of variables declaration//GEN-END:variables
}
